import { useEffect, useRef, useState } from "react";
import { INTERACTION_EVENTS, validateInteractions, validateInteractionReferences, type InteractionDefinition, type InteractionAction, type InteractionCondition, type InteractionRule, type InteractionValue, type Scalar } from "../../../../shared/interactions";
import type { ProjectDefinition } from "../../../../shared/project-definition";
import type { ProjectAsset } from "./assets";
import type { MetricCatalogEntry } from "../../../../shared/component-bindings";

const eventNames: Record<string, string> = { "page.enter": "进入页面", "node.click": "点击组件或模型", "node.change": "控件值改变", "asset.select": "选择设备", "data.change": "指标值变化", "connection.change": "连接状态变化", "state.change": "状态变量变化", custom: "自定义事件" };
const actionNames: Record<InteractionAction["type"], string> = { "state.set": "设置状态", "asset.select": "选择设备", "node.visible": "组件显隐", "page.navigate": "切换页面", delay: "等待", "event.emit": "发出自定义事件", "motion.play": "播放场景动画", "motion.stop": "停止场景动画" };
export type ConditionCatalog = { allowedValueKinds?:InteractionValue["kind"][]; states: InteractionDefinition["states"]; assets: ProjectAsset[]; metrics: MetricCatalogEntry[] };
const literal = (value: Scalar): InteractionValue => ({ kind: "literal", value });

export function ScalarField({ value, onChange, label = "常量值",allowNull = true,strictNumber = false }: { value: Scalar; onChange: (value: Scalar) => void; label?: string;allowNull?:boolean;strictNumber?:boolean }) {
  const type = value === null ? "null" : typeof value;
  return <span className="interaction-fields"><select aria-label={`${label}类型`} value={type} onChange={(event) => onChange(event.target.value === "null" ? null : event.target.value === "number" ? 0 : event.target.value === "boolean" ? false : "")}><option value="string">文本</option><option value="number">数字</option><option value="boolean">布尔值</option>{allowNull ? <option value="null">空值</option>:null}</select>
    {type === "boolean" ? <select aria-label={label} value={String(value)} onChange={(event) => onChange(event.target.value === "true")}><option value="false">否</option><option value="true">是</option></select> : type !== "null" ? <input aria-label={label} type={type === "number" ? "number" : "text"} step="any" required={strictNumber && type === "number"} value={type === "number" && !Number.isFinite(value) ? "":String(value)} onChange={(event) => onChange(type === "number" ? strictNumber && !event.target.value.trim() ? NaN:Number(event.target.value) : event.target.value)} /> : null}</span>;
}
function ValueEditor({ value, onChange, catalog, literalAssets = false }: { value: InteractionValue; onChange: (value: InteractionValue) => void; catalog: ConditionCatalog; literalAssets?: boolean }) {
  return <div className="interaction-fields"><select aria-label="取值来源" value={value.kind} onChange={(event) => onChange(event.target.value === "state" ? { kind: "state", stateId: catalog.states[0]?.id ?? "" } : event.target.value === "event" ? { kind: "event", field: "value" } : event.target.value === "metric" ? { kind: "metric", assetId: catalog.assets[0]?.assetId ?? "", metricKey: catalog.metrics[0]?.metricKey ?? "" } : literal(""))}><option value="literal">常量</option>{(!catalog.allowedValueKinds || catalog.allowedValueKinds.includes("state")) ? <option value="state">状态变量</option>:null}{(!catalog.allowedValueKinds || catalog.allowedValueKinds.includes("event")) ? <option value="event">当前事件</option>:null}<option value="metric">实时指标</option></select>
    {value.kind === "literal" && literalAssets ? <select aria-label="选择目标设备" value={String(value.value ?? "")} onChange={(event) => onChange(literal(event.target.value || null))}><option value="">清空选择</option>{catalog.assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.name}</option>)}</select> : value.kind === "literal" ? <ScalarField value={value.value} onChange={(value) => onChange(literal(value))} /> : value.kind === "state" ? <select aria-label="取值状态" value={value.stateId} onChange={(event) => onChange({ ...value, stateId: event.target.value })}><option value="">选择状态</option>{catalog.states.map((state) => <option key={state.id} value={state.id}>{state.name}</option>)}</select> : value.kind === "event" ? <select aria-label="事件字段" value={value.field} onChange={(event) => onChange({ ...value, field: event.target.value as typeof value.field })}>{["value", "previous", "sourceId", "assetId", "metricKey", "status"].map((field) => <option key={field} value={field}>{field}</option>)}</select> : <><select aria-label="取值设备" value={value.assetId} onChange={(event) => onChange({ ...value, assetId: event.target.value })}><option value="">选择设备</option>{catalog.assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.name}</option>)}</select><input aria-label="取值指标" value={value.metricKey} list="interaction-metrics" onChange={(event) => onChange({ ...value, metricKey: event.target.value })} /></>}
  </div>;
}
const defaultConditionValue = (catalog?:ConditionCatalog):InteractionValue => catalog?.allowedValueKinds && !catalog.allowedValueKinds.includes("event") ? { kind:"metric",assetId:catalog.assets[0]?.assetId ?? "",metricKey:catalog.metrics[0]?.metricKey ?? "" }:{ kind:"event",field:"value" };
const comparison = (catalog?:ConditionCatalog): InteractionCondition => ({ op:"eq",left:defaultConditionValue(catalog),right:literal("") });
export function ConditionEditor({ condition, onChange, catalog, depth = 0 }: { condition: InteractionCondition; onChange: (condition: InteractionCondition) => void; catalog: ConditionCatalog; depth?: number }) {
  return <fieldset className="interaction-condition"><select aria-label="条件比较" value={condition.op} onChange={(event) => {
    const op = event.target.value as InteractionCondition["op"];
    onChange(op === "all" || op === "any" ? { op, conditions: [comparison(catalog)] } : op === "not" ? { op, condition: comparison(catalog) } : op === "exists" ? { op, value: defaultConditionValue(catalog) } : { op, left: "left" in condition ? condition.left : defaultConditionValue(catalog), right: "right" in condition ? condition.right : literal("") });
  }}>{Object.entries({ eq: "等于", ne: "不等于", gt: "大于", gte: "大于等于", lt: "小于", lte: "小于等于", exists: "取值存在", all: "全部满足", any: "任一满足", not: "取反" }).map(([key, text]) => <option key={key} value={key} disabled={depth >= 6 && ["all", "any", "not"].includes(key)}>{text}</option>)}</select>
    {"conditions" in condition ? <>{condition.conditions.map((child, index) => <div key={index}><ConditionEditor condition={child} catalog={catalog} depth={depth + 1} onChange={(next) => onChange({ ...condition, conditions: condition.conditions.map((item, i) => i === index ? next : item) })} /><button type="button" onClick={() => onChange({ ...condition, conditions: condition.conditions.filter((_, i) => i !== index) })}>移除此条件</button></div>)}<button type="button" disabled={condition.conditions.length >= 16} onClick={() => onChange({ ...condition, conditions: [...condition.conditions, comparison(catalog)] })}>添加子条件</button></> : "condition" in condition ? <ConditionEditor condition={condition.condition} catalog={catalog} depth={depth + 1} onChange={(next) => onChange({ op: "not", condition: next })} /> : "value" in condition ? <ValueEditor value={condition.value} catalog={catalog} onChange={(value) => onChange({ ...condition, value })} /> : <><ValueEditor value={condition.left} catalog={catalog} onChange={(left) => onChange({ ...condition, left })} /><ValueEditor value={condition.right} catalog={catalog} onChange={(right) => onChange({ ...condition, right })} /></>}
  </fieldset>;
}

export function InteractionEditor({ project, pageId, assets, metrics, editable, onApply, onClose }: { project: ProjectDefinition; pageId: string; assets: ProjectAsset[]; metrics: MetricCatalogEntry[]; editable: boolean; onApply: (config: InteractionDefinition) => boolean; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [config, setConfig] = useState(() => structuredClone(project.interactions));
  const [selected, setSelected] = useState(config.rules[0]?.id ?? "");
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { dialog.current?.showModal(); }, []);
  const rule = config.rules.find((rule) => rule.id === selected);
  const nodes = project.pages.filter((page) => !rule?.pageId || page.id === rule.pageId).flatMap((page) => page.nodes.map((node) => ({ ...node, label: `${page.name} · ${String(node.props.text ?? node.props.title ?? node.type)} · ${node.id.slice(0, 8)}` })));
  const catalog: ConditionCatalog = { assets, metrics, states: config.states.filter((state) => state.pageId === null || state.pageId === rule?.pageId) };
  const updateRule = (patch: Partial<InteractionRule>) => setConfig({ ...config, rules: config.rules.map((item) => item.id === selected ? { ...item, ...patch } : item) });
  const newAction = (type: InteractionAction["type"]): InteractionAction => {
    if (type === "motion.play" || type === "motion.stop") {
      const node = nodes.find((node) => node.sceneId && project.scenes.find((scene) => scene.id === node.sceneId)?.motions?.length);
      return { type,nodeId: node?.id ?? "",motionId: project.scenes.find((scene) => scene.id === node?.sceneId)?.motions?.[0]?.id ?? "" };
    }
    if (type === "state.set") return { type, stateId: catalog.states[0]?.id ?? "", value: literal(catalog.states[0]?.initial ?? "") };
    if (type === "asset.select") return { type, value: literal(assets[0]?.assetId ?? null), details: true };
    if (type === "node.visible") return { type, nodeId: nodes[0]?.id ?? "", visible: false };
    if (type === "page.navigate") return { type, pageId: project.pages.find((page) => page.id !== pageId)?.id ?? pageId };
    if (type === "event.emit") return { type, name: "custom-event", value: literal("") };
    return { type: "delay", milliseconds: 1000 };
  };
  const updateAction = (index: number, action: InteractionAction) => rule && updateRule({ actions: rule.actions.map((item, i) => i === index ? action : item) });
  const sources = rule ? rule.trigger.type.startsWith("node.") ? nodes.map((node) => ({ id: node.id, name: node.label })) : rule.trigger.type === "state.change" ? catalog.states : rule.trigger.type === "page.enter" ? project.pages : assets.map((asset) => ({ id: asset.assetId, name: asset.name })) : [];
  return <dialog className="model-replacement-dialog interaction-editor" ref={dialog} onCancel={onClose} aria-label="交互编排">
    <header><div><span className="eyebrow">Interactions</span><h2>交互编排</h2></div><button type="button" onClick={onClose}>关闭</button></header>
    <div className="interaction-editor-body"><aside>
      <h3>规则</h3><button type="button" disabled={!editable || config.rules.length >= 200} onClick={() => { const id = crypto.randomUUID(); setConfig({ ...config, rules: [...config.rules, { id, name: "新交互", pageId, enabled: true, reentry: "restart", trigger: { type: "node.click", sourceId: nodes[0]?.id }, condition: null, actions: [] }] }); setSelected(id); }}>添加规则</button>
      {config.rules.map((item) => <button type="button" key={item.id} className={item.id === selected ? "is-active" : ""} onClick={() => setSelected(item.id)}>{item.name}{item.enabled ? "" : " · 已停用"}</button>)}
      <h3>状态变量</h3><button type="button" disabled={!editable || config.states.length >= 100} onClick={() => setConfig({ ...config, states: [...config.states, { id: crypto.randomUUID(), name: "新状态", pageId: null, valueType: "string", initial: "" }] })}>添加状态</button>
      {config.states.map((state) => <fieldset key={state.id} disabled={!editable}><input aria-label="状态名称" value={state.name} onChange={(event) => setConfig({ ...config, states: config.states.map((item) => item.id === state.id ? { ...item, name: event.target.value } : item) })} />
        <select aria-label="状态作用域" value={state.pageId ?? ""} onChange={(event) => setConfig({ ...config, states: config.states.map((item) => item.id === state.id ? { ...item, pageId: event.target.value || null } : item) })}><option value="">项目状态（翻页保留）</option>{project.pages.map((page) => <option key={page.id} value={page.id}>{page.name}（离页重置）</option>)}</select>
        <ScalarField label="状态初始值" value={state.initial} onChange={(initial) => setConfig({ ...config, states: config.states.map((item) => item.id === state.id ? { ...item, initial, valueType: initial === null ? item.valueType : typeof initial as typeof item.valueType } : item) })} />
        <button type="button" onClick={() => setConfig({ ...config, states: config.states.filter((item) => item.id !== state.id) })}>删除状态</button></fieldset>)}
    </aside><section>
      <p>配置只在预览或运行时执行。应用后进入项目撤销历史，仍需保存画布。删除目标前请修复关联规则。</p>
      {rule ? <fieldset disabled={!editable} className="interaction-rule-form">
        <label>规则名称<input aria-label="规则名称" value={rule.name} onChange={(event) => updateRule({ name: event.target.value })} /></label>
        <div className="interaction-fields"><label>作用域<select aria-label="规则作用域" value={rule.pageId ?? ""} onChange={(event) => updateRule({ pageId: event.target.value || null })}><option value="">整个项目</option>{project.pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select></label><label>重复触发<select aria-label="重复触发策略" value={rule.reentry} onChange={(event) => updateRule({ reentry: event.target.value as typeof rule.reentry })}><option value="restart">取消旧执行并重启</option><option value="ignore">忽略新触发</option></select></label><label><input type="checkbox" checked={rule.enabled} onChange={(event) => updateRule({ enabled: event.target.checked })} />启用</label></div>
        <h3>触发事件</h3><div className="interaction-fields"><select aria-label="触发事件" value={rule.trigger.type} onChange={(event) => updateRule({ trigger: { type: event.target.value as typeof rule.trigger.type } })}>{INTERACTION_EVENTS.map((type) => <option key={type} value={type}>{eventNames[type]}</option>)}</select>
          {rule.trigger.type === "custom" ? <input aria-label="事件名称" value={rule.trigger.sourceId ?? ""} onChange={(event) => updateRule({ trigger: { ...rule.trigger, sourceId: event.target.value || undefined } })} /> : <select aria-label="事件来源" value={rule.trigger.sourceId ?? ""} onChange={(event) => updateRule({ trigger: { ...rule.trigger, sourceId: event.target.value || undefined } })}><option value="">作用域内全部来源</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</select>}
          {rule.trigger.type === "data.change" ? <input aria-label="触发指标" placeholder="全部指标" list="interaction-metrics" value={rule.trigger.metricKey ?? ""} onChange={(event) => updateRule({ trigger: { ...rule.trigger, metricKey: event.target.value || undefined } })} /> : null}</div>
        <h3>条件</h3>{rule.condition ? <><ConditionEditor condition={rule.condition} catalog={catalog} onChange={(condition) => updateRule({ condition })} /><button type="button" onClick={() => updateRule({ condition: null })}>移除条件</button></> : <button type="button" onClick={() => updateRule({ condition: comparison() })}>添加条件</button>}
        <h3>顺序动作</h3>{rule.actions.map((action, index) => <fieldset className="interaction-action" key={index}><legend>动作 {index + 1}</legend><div className="interaction-fields"><select aria-label={`动作 ${index + 1} 类型`} value={action.type} onChange={(event) => updateAction(index, newAction(event.target.value as InteractionAction["type"]))}>{Object.entries(actionNames).map(([type, name]) => <option key={type} value={type}>{name}</option>)}</select><button type="button" aria-label={`上移动作 ${index + 1}`} disabled={index === 0} onClick={() => { const actions = [...rule.actions]; [actions[index-1], actions[index]] = [actions[index], actions[index-1]]; updateRule({ actions }); }}>↑</button><button type="button" aria-label={`删除动作 ${index + 1}`} onClick={() => updateRule({ actions: rule.actions.filter((_, i) => i !== index) })}>删除</button></div>
          {action.type === "motion.play" || action.type === "motion.stop" ? <div className="interaction-fields"><select aria-label="动画视窗" value={action.nodeId} onChange={(event) => { const node = nodes.find((node) => node.id === event.target.value); updateAction(index,{ ...action,nodeId: event.target.value,motionId: project.scenes.find((scene) => scene.id === node?.sceneId)?.motions?.[0]?.id ?? "" }); }}><option value="">选择三维视窗</option>{nodes.filter((node) => node.sceneId).map((node) => <option key={node.id} value={node.id}>{node.label}</option>)}</select><select aria-label="动作场景动画" value={action.motionId} onChange={(event) => updateAction(index,{ ...action,motionId: event.target.value })}><option value="">选择动画</option>{(project.scenes.find((scene) => scene.id === nodes.find((node) => node.id === action.nodeId)?.sceneId)?.motions ?? []).map((motion) => <option key={motion.id} value={motion.id}>{motion.name}</option>)}</select><span>播放等待完成后继续；切页取消。</span></div> : null}
          {action.type === "state.set" ? <select aria-label="目标状态" value={action.stateId} onChange={(event) => updateAction(index, { ...action, stateId: event.target.value })}><option value="">选择状态</option>{catalog.states.map((state) => <option key={state.id} value={state.id}>{state.name}</option>)}</select> : null}
          {"value" in action ? <ValueEditor value={action.value} catalog={catalog} literalAssets={action.type === "asset.select"} onChange={(value) => updateAction(index, { ...action, value })} /> : null}
          {action.type === "asset.select" ? <label><input type="checkbox" checked={action.details} onChange={(event) => updateAction(index, { ...action, details: event.target.checked })} />同时打开详情</label> : null}
          {action.type === "event.emit" ? <input aria-label="发出事件名称" value={action.name} onChange={(event) => updateAction(index, { ...action, name: event.target.value })} /> : null}
          {action.type === "delay" ? <label>等待毫秒<input aria-label="等待毫秒" type="number" min={0} max={60000} value={action.milliseconds} onChange={(event) => updateAction(index, { ...action, milliseconds: Number(event.target.value) })} /></label> : null}
          {action.type === "page.navigate" ? <select aria-label="目标页面" value={action.pageId} onChange={(event) => updateAction(index, { ...action, pageId: event.target.value })}>{project.pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select> : null}
          {action.type === "node.visible" ? <div className="interaction-fields"><select aria-label="目标组件" value={action.nodeId} onChange={(event) => updateAction(index, { ...action, nodeId: event.target.value })}>{nodes.map((node) => <option key={node.id} value={node.id}>{node.label}</option>)}</select><select aria-label="目标显隐" value={String(action.visible)} onChange={(event) => updateAction(index, { ...action, visible: event.target.value === "true" })}><option value="false">隐藏</option><option value="true">显示</option></select></div> : null}
        </fieldset>)}<button type="button" disabled={rule.actions.length >= 32} onClick={() => updateRule({ actions: [...rule.actions, newAction("asset.select")] })}>添加动作</button><button type="button" onClick={() => { const copy = { ...structuredClone(rule), id: crypto.randomUUID(), name: `${rule.name.slice(0,95)} 副本` }; setConfig({ ...config, rules: [...config.rules, copy] }); setSelected(copy.id); }}>复制规则</button><button type="button" onClick={() => { setConfig({ ...config, rules: config.rules.filter((item) => item.id !== rule.id) }); setSelected(""); }}>删除规则</button>
      </fieldset> : <p>选择或添加一条规则，配置触发事件、条件和动作。</p>}
      <datalist id="interaction-metrics">{[...new Set(metrics.map((metric) => metric.metricKey))].map((key) => <option key={key} value={key} />)}</datalist>
    </section></div>
    <footer><span role={error ? "alert" : undefined}>{error ?? `${config.rules.length} 条规则 · ${config.states.length} 个状态`}</span><button type="button" onClick={onClose}>取消</button><button type="button" disabled={!editable} onClick={() => { try { const next = validateInteractions(config); validateInteractionReferences(next, project.pages, project.scenes); if (onApply(next)) onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>应用交互配置</button></footer>
  </dialog>;
}
