import type { MetricTransform,MetricTransformStep } from "../../../../shared/metric-transforms";
import { ScalarField } from "./InteractionEditor";
const defaults = (type:MetricTransformStep["type"]):MetricTransformStep => type === "number" ? { type,coerceString:false,scale:1,offset:0 }:type === "enum" ? { type,entries:[{ from:0,to:"stopped" }],unmapped:"error" }:{ type,format:"unix_ms" };
const number = (value:string) => value.trim() ? Number(value):NaN;
export function MetricTransformEditor({ value,onChange,disabled }:{ value:MetricTransform|null;onChange(value:MetricTransform|null):void;disabled:boolean }) {
  const steps = value?.steps ?? [],replace = (index:number,step:MetricTransformStep) => onChange({ version:1,steps:steps.map((item,i) => i === index ? step:item) });
  return <fieldset className="metric-transform-editor" disabled={disabled}><legend>数据转换</legend><p>按顺序处理字段，再按指标类型校验。空值始终保留为空值。</p>
    {steps.map((step,index) => <fieldset key={index} aria-label={`转换步骤 ${index+1}`}><legend>步骤 {index+1}</legend><label>转换类型<select aria-label={`步骤 ${index+1} 转换类型`} value={step.type} onChange={(event) => replace(index,defaults(event.target.value as MetricTransformStep["type"]))}><option value="number">数值换算</option><option value="enum">枚举映射</option><option value="timestamp">时间转换</option></select></label>
      {step.type === "number" ? <><label><input type="checkbox" checked={step.coerceString} onChange={(event) => replace(index,{ ...step,coerceString:event.target.checked })}/>允许数字文本转数值</label><div className="metric-transform-numbers"><label>倍率<input aria-label="转换倍率" required type="number" step="any" value={Number.isFinite(step.scale) ? step.scale:""} onChange={(event) => replace(index,{ ...step,scale:number(event.target.value) })}/></label><label>偏移<input aria-label="转换偏移" required type="number" step="any" value={Number.isFinite(step.offset) ? step.offset:""} onChange={(event) => replace(index,{ ...step,offset:number(event.target.value) })}/></label></div><small>结果 = 输入 × 倍率 + 偏移；需要先减再乘时，添加第二步。</small></>:step.type === "enum" ? <><div className="metric-transform-enums">{step.entries.map((entry,i) => <div key={i} className="metric-transform-enum-row"><label>输入<ScalarField strictNumber label="映射输入" allowNull={false} value={entry.from} onChange={(from) => { if (from !== null) replace(index,{ ...step,entries:step.entries.map((entry,j) => j === i ? { ...entry,from }:entry) }); }}/></label><label>输出<ScalarField strictNumber label="映射输出" value={entry.to} onChange={(to) => replace(index,{ ...step,entries:step.entries.map((entry,j) => j === i ? { ...entry,to }:entry) })}/></label><button type="button" onClick={() => replace(index,{ ...step,entries:step.entries.filter((_,j) => j !== i) })}>删除条目</button></div>)}</div><button type="button" disabled={step.entries.length>=64} onClick={() => replace(index,{ ...step,entries:[...step.entries,{ from:"",to:"" }] })}>添加映射条目</button><label>未匹配时<select aria-label="枚举未匹配策略" value={step.unmapped} onChange={(event) => replace(index,{ ...step,unmapped:event.target.value as "error"|"null" })}><option value="error">明确报错</option><option value="null">保留为空值</option></select></label></>:<label>输入时间格式<select aria-label="转换时间格式" value={step.format} onChange={(event) => replace(index,{ ...step,format:event.target.value as typeof step.format })}><option value="unix_ms">Unix毫秒</option><option value="unix_seconds">Unix秒</option><option value="iso">ISO日期文本</option></select></label>}
      <div className="metric-transform-actions"><button type="button" disabled={index === 0} onClick={() => { const next = [...steps];[next[index-1],next[index]] = [next[index],next[index-1]];onChange({ version:1,steps:next }); }}>上移</button><button type="button" disabled={index === steps.length-1} onClick={() => { const next = [...steps];[next[index+1],next[index]] = [next[index],next[index+1]];onChange({ version:1,steps:next }); }}>下移</button><button type="button" onClick={() => { const next = steps.filter((_,i) => i !== index);onChange(next.length ? { version:1,steps:next }:null); }}>移除此步骤</button></div>
    </fieldset>)}
    {!steps.length ? <p>当前直接使用原字段值，没有转换。</p>:null}<button type="button" disabled={steps.length>=4} onClick={() => onChange({ version:1,steps:[...steps,defaults("number")] })}>添加转换步骤</button>{steps.length ? <button type="button" onClick={() => onChange(null)}>清除全部转换</button>:null}
  </fieldset>;
}
