import { test,expect,request as apiRequest } from "@playwright/test";
import { createServer } from "node:http";
import { once } from "node:events";
import { randomBytes } from "node:crypto";
import { nodeRuntimeFixture } from "./node-runtime-fixture";
import { createDemo } from "./demo";

test("edit ordered metric transforms and source time units, reopen and display converted live values with explicit failures",async ({ browser },testInfo) => {
  test.setTimeout(90000);let temperature:unknown = "140";
  const upstream = createServer((request,response) => response.end(JSON.stringify({ timestamp:Date.now()/1000,values:{ temperature:request.url === "/numeric" ? 60:temperature,pressure:24,status:"running",alarmLevel:0 } })));
  upstream.listen(0,"127.0.0.1");await once(upstream,"listening");const host = `127.0.0.1:${(upstream.address() as import("node:net").AddressInfo).port}`;
  const runtime = await nodeRuntimeFixture(testInfo,[host]),api = await apiRequest.newContext({ baseURL:runtime.url });let context:Awaited<ReturnType<typeof browser.newContext>>|undefined;
  try {
    expect((await api.post("/api/v1/auth/bootstrap",{ headers:{ "x-bootstrap-token":runtime.bootstrap },data:{ email:"transform-ui@example.invalid",password:randomBytes(24).toString("hex"),displayName:"Transform UI" } })).status()).toBe(201);
    const demo = await createDemo(api),base = `/api/v1/projects/${demo.projectId}`,assetPath = `${base}/assets/${demo.assets[0].id}`;
    const sources = (await (await api.get(`${base}/data-sources`)).json()).dataSources;
    const sourceId = (await (await api.get(`${assetPath}/data-bindings`)).json()).dataBindings[0].dataSourceId;
    for (const source of sources) expect((await api.patch(`${base}/data-sources/${source.id}`,{ data:{ config:{ ...source.config,url:`http://${host}/${source.id === sourceId ? "state":"numeric"}`,timestampFormat:"unix_seconds",intervalSeconds:1 } } })).status()).toBe(200);
    // The UI must preserve an old source without a format until the user explicitly selects one.
    const source = sources.find((source:{id:string}) => source.id === sourceId);expect((await api.patch(`${base}/data-sources/${source.id}`,{ data:{ config:{ ...source.config,url:`http://${host}/state`,intervalSeconds:1 } } })).status()).toBe(200);
    context = await browser.newContext({ storageState:await api.storageState(),viewport:{ width:1440,height:1000 } });const page = await context.newPage();
    await page.goto(`${runtime.url}/#/projects/${demo.projectId}/canvas`);await page.getByRole("button",{ name:"数据源",exact:true }).click();await page.getByRole("button",{ name:new RegExp(source.name) }).click();
    await page.getByLabel("源时间格式",{ exact:true }).selectOption("unix_seconds");await page.getByRole("button",{ name:"保存修改",exact:true }).click();await page.getByRole("button",{ name:"关闭数据源配置",exact:true }).click();
    const open = async () => { await page.getByRole("button",{ name:"资产与指标",exact:true }).click();const panel = page.getByRole("dialog",{ name:"资产与指标",exact:true });await panel.getByRole("combobox",{ name:"当前设备",exact:true }).selectOption(demo.assets[0].id);await panel.locator(".asset-data-binding-list").getByRole("button",{ name:/^temperature/ }).click();return panel; };
    let panel = await open();await panel.getByRole("button",{ name:"添加转换步骤",exact:true }).click();let first = panel.getByRole("group",{ name:"转换步骤 1",exact:true });await first.getByLabel("允许数字文本转数值").check();await first.getByLabel("转换偏移",{ exact:true }).fill("-32");
    await panel.getByRole("button",{ name:"添加转换步骤",exact:true }).click();const second = panel.getByRole("group",{ name:"转换步骤 2",exact:true });await second.getByLabel("转换倍率",{ exact:true }).fill(String(5/9));
    await second.getByRole("button",{ name:"上移",exact:true }).click();await panel.getByRole("group",{ name:"转换步骤 1",exact:true }).getByRole("button",{ name:"下移",exact:true }).click();
    await panel.getByRole("button",{ name:"保存修改",exact:true }).click();await expect(panel.getByRole("status")).toHaveText("指标映射已更新。");await page.screenshot({ path:testInfo.outputPath("metric-transform-editor.png") });
    await panel.getByRole("button",{ name:"关闭资产与指标",exact:true }).click();await page.reload();panel = await open();first = panel.getByRole("group",{ name:"转换步骤 1",exact:true });await expect(first.getByLabel("转换偏移",{ exact:true })).toHaveValue("-32");await expect(first.getByLabel("允许数字文本转数值")).toBeChecked();await expect(panel.getByRole("group",{ name:"转换步骤 2",exact:true }).getByLabel("转换倍率",{ exact:true })).toHaveValue(String(5/9));
    await panel.locator(".asset-data-binding-list").getByRole("button",{ name:/^pressure/ }).click();await panel.getByRole("button",{ name:"添加转换步骤",exact:true }).click();await panel.getByLabel("步骤 1 转换类型",{ exact:true }).selectOption("enum");
    await panel.getByLabel("映射输入",{ exact:true }).fill("");await panel.getByRole("button",{ name:"保存修改",exact:true }).click();await expect(panel.getByLabel("映射输入",{ exact:true })).toHaveValue("");expect((await (await api.get(`${assetPath}/data-bindings`)).json()).dataBindings.find((binding:{metricKey:string}) => binding.metricKey === "pressure")).not.toHaveProperty("transform");
    await panel.getByLabel("映射输入",{ exact:true }).fill("24");await panel.getByLabel("映射输出类型",{ exact:true }).selectOption("number");await panel.getByLabel("映射输出",{ exact:true }).fill("0.5");await panel.getByRole("button",{ name:"保存修改",exact:true }).click();await expect(panel.getByRole("status")).toHaveText("指标映射已更新。");
    await panel.getByRole("button",{ name:"＋ 新建",exact:true }).click();await panel.getByLabel("指标键 metricKey",{ exact:true }).fill("reportedAt");await panel.getByLabel("响应字段路径",{ exact:true }).fill("$.timestamp");await panel.getByRole("combobox",{ name:"值类型",exact:true }).selectOption("timestamp");await panel.getByRole("button",{ name:"添加转换步骤",exact:true }).click();await panel.getByLabel("步骤 1 转换类型",{ exact:true }).selectOption("timestamp");await panel.getByLabel("转换时间格式",{ exact:true }).selectOption("unix_seconds");await panel.getByRole("button",{ name:"创建映射",exact:true }).click();await expect(panel.getByRole("status")).toHaveText("指标映射已创建。");
    const actual = (await (await api.get(`${assetPath}/runtime-state`)).json()).runtimeState;expect(actual.values.pressure).toBe(0.5);expect(Math.abs(Date.now()-Date.parse(actual.values.reportedAt))).toBeLessThan(6000);
    await panel.getByRole("button",{ name:"关闭资产与指标",exact:true }).click();await page.getByRole("button",{ name:"预览",exact:true }).click();const metric = page.locator('[data-node-id="fixed-metric"] [data-binding-state]');await expect(metric).toHaveAttribute("data-binding-state","live");await expect(metric.locator(".dashboard-metric-value strong")).toHaveText("60");await expect(page.locator(".runtime-status-banner")).toContainText("在线 2 台");await page.screenshot({ path:testInfo.outputPath("metric-transform-runtime.png") });
    temperature = "unmatched-private-fixture";await expect(metric).toHaveAttribute("data-binding-state","transform-error");await expect(metric).toContainText("转换错误");await expect(page.locator("body")).not.toContainText("unmatched-private-fixture");temperature = "140";await expect(metric).toHaveAttribute("data-binding-state","live");
    const draft = (await (await api.get(`${base}/publication-draft`)).json()).draft,freeze = await api.post(`${base}/versions`,{ data:{ expectedRuntimeRevision:draft.runtimeRevision,label:"Frozen metric conversion" } });expect(freeze.status(),await freeze.text()).toBe(201);const version = (await freeze.json()).version;
    const activated = await api.post(`${base}/versions/${version.id}/activate`,{ data:{ expectedPublicationRevision:0 } });expect(activated.status(),await activated.text()).toBe(200);
    await page.getByRole("link",{ name:"返回编辑",exact:true }).click();panel = await open();await panel.getByRole("button",{ name:"清除全部转换",exact:true }).click();await panel.getByRole("button",{ name:"保存修改",exact:true }).click();await expect(panel.getByRole("status")).toHaveText("指标映射已更新。");
    expect((await (await api.get(`${assetPath}/data-bindings`)).json()).dataBindings.find((binding:{metricKey:string}) => binding.metricKey === "temperature")).not.toHaveProperty("transform");
    await page.goto(`${runtime.url}/#/projects/${demo.projectId}/versions/${version.id}/run`);await expect(page.locator('[data-node-id="fixed-metric"] [data-binding-state]')).toHaveAttribute("data-binding-state","live");await expect(page.locator('[data-node-id="fixed-metric"] .dashboard-metric-value strong')).toHaveText("60");await page.screenshot({ path:testInfo.outputPath("frozen-metric-transform.png") });
  } finally { await context?.close();await api.dispose();await runtime.dispose();upstream.closeAllConnections();await new Promise<void>((resolve) => upstream.close(() => resolve())); }
});
