import {unzipSync} from "fflate";
import {test,expect,request as apiRequest} from '@playwright/test';
import {randomBytes} from 'node:crypto';
import {nodeRuntimeFixture} from './node-runtime-fixture';
import {createDemo} from './demo';
import {createAnimatedMockGltf} from '../scripts/mock-model.mjs';
import {createEditorState,executeEditorOperation} from '../shared/editor-operations';
import {projectDefinitionPatch} from '../shared/project-definition';
import {DEFAULT_SCENE_SETTINGS,IDENTITY_TRANSFORM} from '../shared/scene-definition';

test('generate a compressed model version in the editor, preserve object and clip identities, undo and independently import',async({browser},testInfo)=>{
 test.setTimeout(90000);const runtime=await nodeRuntimeFixture(testInfo),api=await apiRequest.newContext({baseURL:runtime.url});let context:Awaited<ReturnType<typeof browser.newContext>>|undefined,sourceClosed=false,target:Awaited<ReturnType<typeof nodeRuntimeFixture>>|undefined,targetApi:Awaited<ReturnType<typeof apiRequest.newContext>>|undefined;
 try{
  expect((await api.post('/api/v1/auth/bootstrap',{headers:{'x-bootstrap-token':runtime.bootstrap},data:{email:'optimization-ui@example.invalid',password:randomBytes(24).toString('hex'),displayName:'Optimization'}})).status()).toBe(201);
  const demo=await createDemo(api,true),base=`/api/v1/projects/${demo.projectId}`,bytes=createAnimatedMockGltf(),uploaded=await api.post(`${base}/model-assets?filename=animated.gltf`,{data:bytes,headers:{'content-type':'model/gltf+json'}});expect(uploaded.status()).toBe(201);const original=(await uploaded.json()).modelAsset,object=original.inspection.objects.find((object:{mesh:boolean})=>object.mesh),clip=original.inspection.clips[0];
  const instance={id:'optimized-instance',name:'压缩实例',modelAssetId:original.id,transform:structuredClone(IDENTITY_TRANSFORM),visible:true,appearance:null,objectTransforms:{},objectAppearances:{[object.objectId]:{color:'#ffcc00',opacity:.7,visible:true}}};
  let state=createEditorState((await(await api.get(`${base}/definition`)).json()).definition);state=executeEditorOperation(state,{type:'scene.extract',nodeId:'demo-model',scene:{id:'optimized-scene',name:'可压缩动画场景',settings:DEFAULT_SCENE_SETTINGS,instances:[instance,{...structuredClone(instance),id:'unchanged-instance',name:'保持旧版',transform:{...structuredClone(IDENTITY_TRANSFORM),position:[4,0,0]}}],assetBindings:[{id:'asset-reference',instanceId:instance.id,objectId:object.objectId,assetId:'DEVICE-001'}],motions:[{id:'native-motion',name:'原生动画',version:1,durationMs:500,repeat:1,fill:'restore',tracks:[{id:'native-track',type:'clip',target:{instanceId:instance.id,objectId:null},property:'clip',clipId:clip.clipId,easing:'linear',keyframes:[{timeMs:0,value:clip.startTime},{timeMs:500,value:clip.duration}]}]}]}});
  const saved=await api.patch(`${base}/definition`,{data:projectDefinitionPatch(state.project,state.savedProject)});expect(saved.status(),await saved.text()).toBe(200);
  context=await browser.newContext({storageState:await api.storageState()});const page=await context.newPage();await page.goto(`${runtime.url}/#/projects/${demo.projectId}/3d-editor/demo-model`);await page.locator('.scene-instance-list').getByRole('button',{name:/压缩实例/}).click();await page.getByRole('button',{name:'模型版本与替换',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'模型版本与映射修复',exact:true});await dialog.getByRole('button',{name:'生成Meshopt压缩版本',exact:true}).click();await expect(dialog.locator('.model-optimization-report')).toContainText('逐字节验证');
  const optimized=(await(await api.get(`${base}/model-assets/${original.id}/versions`)).json()).modelAssets[0];expect(optimized.previousVersionId).toBe(original.id);expect(optimized.inspection.objects).toEqual(original.inspection.objects);expect(optimized.inspection.clips).toEqual(original.inspection.clips);expect(optimized.inspection.optimization.sourceSha256).toBe(original.sha256);
  await expect(dialog.locator('.model-reference-list')).toContainText('稳定标识保留');await expect(dialog.locator('.replacement-viewport .model-3d-edit-hint')).toBeVisible();await dialog.getByRole('button',{name:'预览新片段',exact:true}).click();await expect(dialog).toContainText('片段预览完成');await page.screenshot({path:testInfo.outputPath('model-optimization-preview.png')});await dialog.getByRole('button',{name:'应用替换与修复',exact:true}).click();await page.getByRole('button',{name:'保存并返回',exact:true}).click();
  const after=(await(await api.get(`${base}/definition`)).json()).definition;expect(after.scenes[0].instances[0].modelAssetId).toBe(optimized.id);expect(after.scenes[0].instances[1].modelAssetId).toBe(original.id);expect(after.scenes[0].assetBindings).toEqual(state.project.scenes[0].assetBindings);expect(after.scenes[0].motions).toEqual(state.project.scenes[0].motions);
  await page.getByRole('button',{name:'撤销',exact:true}).click();await page.getByRole('button',{name:'保存画布',exact:true}).click();await expect.poll(async()=>(await(await api.get(`${base}/definition`)).json()).definition.scenes[0].instances[0].modelAssetId).toBe(original.id);await page.getByRole('button',{name:'重做',exact:true}).click();await page.getByRole('button',{name:'保存画布',exact:true}).click();await expect.poll(async()=>(await(await api.get(`${base}/definition`)).json()).definition.scenes[0].instances[0].modelAssetId).toBe(optimized.id);
  const draft=(await(await api.get(`${base}/publication-draft`)).json()).draft,freeze=await api.post(`${base}/versions`,{data:{expectedRuntimeRevision:draft.runtimeRevision,label:'Verified compressed version'}});expect(freeze.status(),await freeze.text()).toBe(201);const version=(await freeze.json()).version,exported=await api.get(`${base}/versions/${version.id}/package`);expect(exported.status()).toBe(200);const check=await api.post('/api/v1/project-packages',{data:await exported.body(),headers:{'content-type':'application/zip'}});expect(check.status(),await check.text()).toBe(201);
  expect(await(await api.get(`${base}/model-assets/${original.id}/content`)).text()).toBe(bytes);const forged=await api.post(`${base}/model-assets?filename=claim.glb`,{data:await(await api.get(`${base}/model-assets/${optimized.id}/content`)).body(),headers:{'content-type':'model/gltf-binary'}});expect(forged.status()).toBe(400);expect((await forged.json()).error).toBe('model_derivation_required');
  const projectZip=await exported.body(),manifest=JSON.parse(new TextDecoder().decode(unzipSync(projectZip)['manifest.json'])),sourceConfigs=(await(await api.get(`${base}/data-sources`)).json()).dataSources;
  await context.close();context=undefined;target=await nodeRuntimeFixture({...testInfo,outputPath:(...parts:string[])=>testInfo.outputPath('target',...parts)} as typeof testInfo);targetApi=await apiRequest.newContext({baseURL:target.url});expect((await targetApi.post('/api/v1/auth/bootstrap',{headers:{'x-bootstrap-token':target.bootstrap},data:{email:'compression-target@example.invalid',password:randomBytes(24).toString('hex'),displayName:'Compression target'}})).status()).toBe(201);
  const checked=await targetApi.post('/api/v1/project-packages',{data:projectZip,headers:{'content-type':'application/zip'}});expect(checked.status(),await checked.text()).toBe(201);const installed=await targetApi.post('/api/v1/project-packages/install',{data:{inspectionId:(await checked.json()).inspection.id,projectName:'独立压缩模型交付'}});expect(installed.status(),await installed.text()).toBe(201);const installation=(await installed.json()).installation,identity=await targetApi.storageState();
  const endpoints=Object.fromEntries(manifest.snapshot.dataSources.map((source:any)=>[source.config.endpointRef,{projectIds:[installation.projectId],url:sourceConfigs.find((item:any)=>item.id===source.id).config.url}]));await target.setSources({version:1,endpoints,credentials:{}});await targetApi.dispose();targetApi=undefined;const targetUrl=await target.restart();targetApi=await apiRequest.newContext({baseURL:targetUrl,storageState:identity});await runtime.dispose();sourceClosed=true;
  const activate=await targetApi.post(`/api/v1/projects/${installation.projectId}/versions/${installation.versionId}/activate`,{data:{expectedPublicationRevision:0}});expect(activate.status(),await activate.text()).toBe(200);context=await browser.newContext({storageState:identity});const running=await context.newPage();await running.goto(`${targetUrl}/#/projects/${installation.projectId}/run`);await expect(running.locator('.model-3d-edit-hint')).toBeVisible();await expect(running.locator('.runtime-status-banner')).toContainText('在线 2 台');await running.getByRole('button',{name:'选择设备 DEVICE-001',exact:true}).click();await expect(running.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText(/4\d/);await running.screenshot({path:testInfo.outputPath('independent-compressed-runtime.png')});
 }finally{await context?.close();await targetApi?.dispose();await target?.dispose();await api.dispose();if(!sourceClosed)await runtime.dispose();}
});
