import { unzipSync } from "fflate";
import { test,expect,request as apiRequest } from "@playwright/test";
import { Aedes } from "aedes";
import { createServer,type Socket } from "node:net";
import { once } from "node:events";
import { randomBytes } from "node:crypto";
import { nodeRuntimeFixture } from "./node-runtime-fixture";
import { createDemo } from "./demo";

test("MQTT UI config shares an authenticated broker, reconnects, persists history and alarms without viewers and freezes across restart",async ({ browser },testInfo) => {
  test.setTimeout(120000);let accepting = true,stale = false,temperature = 43.8,connections = 0,subscriptions = 0;
  const username = "mqtt-fixture-user",password = randomBytes(24).toString("hex"),sockets = new Set<Socket>();
  const broker = await Aedes.createBroker({ authenticate:(_client,user,secret,callback) => callback(null,accepting && user === username && secret?.toString() === password),authorizeSubscribe:(_client,subscription,callback) => { subscriptions++;callback(null,subscription.topic === "devices/snapshot" ? subscription:null); } });
  const server = createServer((socket) => { connections++;sockets.add(socket);socket.once("close",() => sockets.delete(socket));broker.handle(socket); });server.listen(0,"127.0.0.1");await once(server,"listening");const host = `127.0.0.1:${(server.address() as import("node:net").AddressInfo).port}`;
  const timer = setInterval(() => broker.publish({ cmd:"publish",qos:1,dup:false,retain:true,topic:"devices/snapshot",payload:Buffer.from(JSON.stringify({ timestamp:(Date.now()-(stale ? 60000:0))/1000,values:{ temperature,pressure:24,status:"running",alarmLevel:0 } })) },() => {}),50);
  const runtime = await nodeRuntimeFixture(testInfo,[host]);let api = await apiRequest.newContext({ baseURL:runtime.url });const contexts:Array<Awaited<ReturnType<typeof browser.newContext>>> = [];
  try {
    expect((await api.post("/api/v1/auth/bootstrap",{ headers:{ "x-bootstrap-token":runtime.bootstrap },data:{ email:"mqtt-runtime@example.invalid",password:randomBytes(24).toString("hex"),displayName:"MQTT runtime" } })).status()).toBe(201);
    const demo = await createDemo(api,true),base = `/api/v1/projects/${demo.projectId}`,sources = (await (await api.get(`${base}/data-sources`)).json()).dataSources,source = sources[0];
    for (const asset of demo.assets) for (const binding of (await (await api.get(`${base}/assets/${asset.id}/data-bindings`)).json()).dataBindings) expect((await api.patch(`${base}/assets/${asset.id}/data-bindings/${binding.id}`,{ data:{ dataSourceId:source.id } })).status()).toBe(200);
    const environment = { version:1,endpoints:{},credentials:{},mqttEndpoints:{ broker:{ projectIds:[demo.projectId],url:`mqtt://${host}`,topics:["devices/snapshot"],credentialRef:"device" } },mqttCredentials:{ device:{ username,password } } };
    await runtime.setSources(environment);const identity = await api.storageState();await api.dispose();let url = await runtime.restart();api = await apiRequest.newContext({ baseURL:url,storageState:identity });
    const editor = await browser.newContext({ storageState:identity });contexts.push(editor);const editPage = await editor.newPage();await editPage.goto(`${url}/#/projects/${demo.projectId}/canvas`);await editPage.getByRole("button",{ name:"数据源",exact:true }).click();await editPage.getByRole("button",{ name:new RegExp(source.name) }).click();
    await editPage.getByRole("combobox",{ name:"连接类型",exact:true }).selectOption("mqtt");await editPage.getByLabel("环境端点引用（必填）",{ exact:true }).fill("broker");await editPage.getByLabel("MQTT订阅主题",{ exact:true }).fill("devices/snapshot");await editPage.getByLabel("数据时间戳路径",{ exact:true }).fill("$.timestamp");await editPage.getByLabel("源时间格式",{ exact:true }).selectOption("unix_seconds");await editPage.getByLabel("心跳周期（秒）",{ exact:true }).fill("5");await editPage.getByLabel("最大重连间隔（秒）",{ exact:true }).fill("5");
    await editPage.getByRole("button",{ name:"保存修改",exact:true }).click();await editPage.getByRole("button",{ name:"测试连接并发现字段",exact:true }).click();await expect(editPage.locator(".data-source-probe-result")).toBeVisible();await editPage.screenshot({ path:testInfo.outputPath("mqtt-source-configuration.png") });
    const saved = (await (await api.get(`${base}/data-sources`)).json()).dataSources.find((item:{id:string}) => item.id === source.id);expect(saved).toMatchObject({ sourceType:"mqtt",config:{ url:"",endpointRef:"broker",topic:"devices/snapshot",timestampFormat:"unix_seconds" } });expect(JSON.stringify(saved)).not.toContain(password);expect(JSON.stringify(saved)).not.toContain(host);
    await editor.close();contexts.shift();await expect.poll(() => sockets.size).toBe(0);const baseline = connections,subscriptionBaseline = subscriptions,pages = [];
    for (let index=0;index<2;index++) { const context = await browser.newContext({ storageState:identity });contexts.push(context);const page = await context.newPage();pages.push(page);await page.goto(`${url}/#/projects/${demo.projectId}/preview`);await expect(page.locator(".runtime-status-banner")).toContainText("在线 2 台");await page.getByRole("button",{ name:"选择设备 DEVICE-001",exact:true }).click(); }
    expect(connections-baseline).toBe(1);expect(subscriptions-subscriptionBaseline).toBe(1);expect(sockets.size).toBe(1);temperature = 68.5;await expect(pages[1].locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.5");
    accepting = false;for (const socket of sockets) socket.destroy();await expect(pages[1].locator(".runtime-status-banner")).toContainText("失联");accepting = true;await expect(pages[1].locator(".runtime-status-banner")).toContainText("在线 2 台");expect(subscriptions-subscriptionBaseline).toBeGreaterThan(1);
    stale = true;await expect(pages[1].locator(".runtime-status-banner")).toContainText("陈旧");stale = false;await expect(pages[1].locator(".runtime-status-banner")).toContainText("在线 2 台");await pages[1].screenshot({ path:testInfo.outputPath("mqtt-two-browsers.png") });
    await contexts.shift()!.close();expect(sockets.size).toBe(1);await contexts.shift()!.close();await expect.poll(() => sockets.size).toBe(0);
    expect((await api.patch(`${base}/data-sources/${source.id}`,{ data:{ config:{ ...saved.config,collectionMode:"continuous" } } })).status()).toBe(200);
    const alarmConfig = (await (await api.get(`${base}/alarm-rules`)).json());expect((await api.put(`${base}/alarm-rules`,{ data:{ expectedRuntimeRevision:alarmConfig.runtimeRevision,rules:[{ id:"mqtt-temperature",name:"MQTT temperature",assetId:"DEVICE-001",enabled:true,severity:"warning",message:"MQTT high",recoveryCondition:null,condition:{ op:"gt",left:{ kind:"metric",assetId:"DEVICE-001",metricKey:"temperature" },right:{ kind:"literal",value:60 } } }] } })).status()).toBe(200);
    const alarms = async (versionId?:string) => (await (await api.get(`${base}${versionId ? `/versions/${versionId}`:""}/alarms`)).json());await expect.poll(async () => (await alarms()).active.length).toBe(1);
    await expect.poll(async () => (await (await api.get(`${base}/telemetry/history?assetId=DEVICE-001&metricKey=temperature`)).json()).records.some((row:{value:number;quality:string}) => row.value === 68.5 && row.quality === "good")).toBe(true);
    const draft = (await (await api.get(`${base}/publication-draft`)).json()).draft,freeze = await api.post(`${base}/versions`,{ data:{ expectedRuntimeRevision:draft.runtimeRevision,label:"Frozen MQTT" } });expect(freeze.status(),await freeze.text()).toBe(201);const version = (await freeze.json()).version,activated = await api.post(`${base}/versions/${version.id}/activate`,{ data:{ expectedPublicationRevision:0 } });expect(activated.status(),await activated.text()).toBe(200);
    const binding = (await (await api.get(`${base}/assets/${demo.assets[0].id}/data-bindings`)).json()).dataBindings.find((binding:{metricKey:string}) => binding.metricKey === "temperature");expect((await api.patch(`${base}/assets/${demo.assets[0].id}/data-bindings/${binding.id}`,{ data:{ transform:{ version:1,steps:[{ type:"number",coerceString:false,scale:0,offset:10 }] } } })).status()).toBe(200);
    await api.dispose();url = await runtime.restart();api = await apiRequest.newContext({ baseURL:url,storageState:identity });await expect.poll(async () => (await alarms(version.id)).active[0]?.confirmation).toBe("known");await expect.poll(async () => (await alarms()).active.length).toBe(0);expect(sockets.size).toBe(2);
    const context = await browser.newContext({ storageState:identity });contexts.push(context);const page = await context.newPage();await page.goto(`${url}/#/projects/${demo.projectId}/versions/${version.id}/run`);await page.getByRole("button",{ name:"选择设备 DEVICE-001",exact:true }).click();await expect(page.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.5");await page.screenshot({ path:testInfo.outputPath("mqtt-frozen-runtime.png") });
    const exported = await api.get(`${base}/versions/${version.id}/package`);expect(exported.status()).toBe(200);const zip = await exported.body(),manifestText = new TextDecoder().decode(unzipSync(zip)["manifest.json"]),manifest = JSON.parse(manifestText);expect(manifest.snapshot.requiredCapabilities).toContain("mqtt-source-v1");expect(manifestText).not.toContain(password);expect(manifestText).not.toContain(host);
    const inspected = await api.post("/api/v1/project-packages",{ data:zip,headers:{ "content-type":"application/zip" } });expect(inspected.status(),await inspected.text()).toBe(201);const installed = await api.post("/api/v1/project-packages/install",{ data:{ inspectionId:(await inspected.json()).inspection.id,projectName:"Imported MQTT" } });expect(installed.status(),await installed.text()).toBe(201);const installation = (await installed.json()).installation,importedBase = `/api/v1/projects/${installation.projectId}`;
    const preview = (await (await api.get(`${importedBase}/versions/${installation.versionId}/restore-draft`)).json()).preview;expect((await api.post(`${importedBase}/versions/${installation.versionId}/restore-draft`,{ data:{ expectedRuntimeRevision:preview.expectedRuntimeRevision } })).status()).toBe(200);const importedSources = (await (await api.get(`${importedBase}/data-sources`)).json()).dataSources,importedMqtt = importedSources.find((item:{sourceType:string}) => item.sourceType === "mqtt");expect(importedMqtt.id).not.toBe(source.id);expect(importedMqtt.config).toEqual(manifest.snapshot.dataSources.find((item:{sourceType:string}) => item.sourceType === "mqtt").config);
    expect((await api.post(`${importedBase}/versions/${installation.versionId}/activate`,{ data:{ expectedPublicationRevision:0 } })).status()).toBe(409);
    while (contexts.length) await contexts.shift()!.close();environment.mqttEndpoints.broker.projectIds.push(installation.projectId);await runtime.setSources(environment);await api.dispose();url = await runtime.restart();api = await apiRequest.newContext({ baseURL:url,storageState:identity });const activatedImport = await api.post(`${importedBase}/versions/${installation.versionId}/activate`,{ data:{ expectedPublicationRevision:0 } });expect(activatedImport.status(),await activatedImport.text()).toBe(200);
    const importedContext = await browser.newContext({ storageState:identity });contexts.push(importedContext);const importedPage = await importedContext.newPage();await importedPage.goto(`${url}/#/projects/${installation.projectId}/run`);await expect(importedPage.locator(".runtime-status-banner")).toContainText("在线 2 台");await importedPage.getByRole("button",{ name:"选择设备 DEVICE-001",exact:true }).click();await expect(importedPage.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.5");await importedPage.screenshot({ path:testInfo.outputPath("imported-mqtt-runtime.png") });
  } finally { for (const context of contexts) await context.close();await api.dispose();await runtime.dispose();clearInterval(timer);for (const socket of sockets) socket.destroy();await new Promise<void>((resolve) => broker.close(resolve));await new Promise<void>((resolve) => server.close(() => resolve())); }
});
