import { test,expect,request as apiRequest } from "@playwright/test";
import { DatabaseSync } from "node:sqlite";
import { randomBytes } from "node:crypto";
import { mkdir,writeFile } from "node:fs/promises";
import { join,dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { unzipSync } from "fflate";
import { nodeRuntimeFixture } from "./node-runtime-fixture";
import { createDemo } from "./demo";

test("downloaded standalone runtime includes and executes the read-only query worker after the original host stops",async ({ browser },testInfo) => {
  test.setTimeout(90000);const source = await nodeRuntimeFixture(testInfo),original = await apiRequest.newContext({ baseURL:source.url });let sourceClosed = false,independent:{ url:string;close():Promise<void> }|undefined,api:Awaited<ReturnType<typeof apiRequest.newContext>>|undefined,context:Awaited<ReturnType<typeof browser.newContext>>|undefined;
  const databasePath = testInfo.outputPath("equipment.sqlite"),db = new DatabaseSync(databasePath);db.exec("CREATE TABLE equipment(assetId TEXT PRIMARY KEY,temperature REAL,pressure REAL,status TEXT,alarmLevel INTEGER); INSERT INTO equipment VALUES('DEVICE-001',66.2,24,'running',0),('DEVICE-002',68.3,25,'running',0)");db.close();
  try {
    expect((await original.post("/api/v1/auth/bootstrap",{ headers:{ "x-bootstrap-token":source.bootstrap },data:{ email:"sql-distribution-source@example.invalid",password:randomBytes(24).toString("hex"),displayName:"SQL source" } })).status()).toBe(201);const demo = await createDemo(original),base = `/api/v1/projects/${demo.projectId}`,dataSource = (await (await original.get(`${base}/data-sources`)).json()).dataSources[0];
    for (const asset of demo.assets) for (const binding of (await (await original.get(`${base}/assets/${asset.id}/data-bindings`)).json()).dataBindings) expect((await original.patch(`${base}/assets/${asset.id}/data-bindings/${binding.id}`,{ data:{ dataSourceId:dataSource.id,sourcePath:`$.records.${asset.assetId}.${binding.metricKey}` } })).status()).toBe(200);
    expect((await original.patch(`${base}/data-sources/${dataSource.id}`,{ data:{ sourceType:"sqlite_query",config:{ url:"",queryRef:"equipment",credentialRef:null,intervalSeconds:1,timeoutMs:1000,timestampPath:null } } })).status()).toBe(200);const draft = (await (await original.get(`${base}/publication-draft`)).json()).draft,created = await original.post(`${base}/versions`,{ data:{ expectedRuntimeRevision:draft.runtimeRevision,label:"SQL standalone" } });expect(created.status(),await created.text()).toBe(201);const version = (await created.json()).version,projectZip = await (await original.get(`${base}/versions/${version.id}/package`)).body();
    const download = await original.get("/api/v1/runtime/distribution");expect(download.status()).toBe(200);const files = unzipSync(await download.body());expect(Object.keys(files)).toContain("sqlite-query-worker.mjs");const clean = testInfo.outputPath("clean-runtime");
    for (const [name,bytes] of Object.entries(files)) { expect(name.startsWith("/") || name.includes("..") || name.includes("\\")).toBe(false);const filename = join(clean,name);await mkdir(dirname(filename),{ recursive:true });await writeFile(filename,bytes,{ mode:0o600 }); }
    await source.dispose();sourceClosed = true;const { startRuntime } = await import(pathToFileURL(join(clean,"server.mjs")).href),bootstrap = randomBytes(24).toString("hex"),options = { dataDirectory:join(clean,"data"),port:0,environment:{ BOOTSTRAP_TOKEN:bootstrap,RUNTIME_POLLING_ENABLED:"true" } };
    independent = await startRuntime(options);api = await apiRequest.newContext({ baseURL:independent!.url });expect((await api.post("/api/v1/auth/bootstrap",{ headers:{ "x-bootstrap-token":bootstrap },data:{ email:"sql-clean@example.invalid",password:randomBytes(24).toString("hex"),displayName:"SQL clean" } })).status()).toBe(201);
    const checked = await api.post("/api/v1/project-packages",{ data:projectZip,headers:{ "content-type":"application/zip" } });expect(checked.status(),await checked.text()).toBe(201);const installed = await api.post("/api/v1/project-packages/install",{ data:{ inspectionId:(await checked.json()).inspection.id,projectName:"独立SQLite交付" } });expect(installed.status(),await installed.text()).toBe(201);const installation = (await installed.json()).installation,identity = await api.storageState();await api.dispose();api = undefined;await independent!.close();independent = undefined;
    independent = await startRuntime({ ...options,sourceEnvironment:{ version:1,endpoints:{},credentials:{},sqliteQueries:{ equipment:{ projectIds:[installation.projectId],databasePath,sql:"SELECT * FROM equipment ORDER BY assetId",parameters:[],tables:{ equipment:["assetId","temperature","pressure","status","alarmLevel"] },rowKey:"assetId",maxRows:10 } } } });api = await apiRequest.newContext({ baseURL:independent!.url,storageState:identity });const path = `/api/v1/projects/${installation.projectId}`,activated = await api.post(`${path}/versions/${installation.versionId}/activate`,{ data:{ expectedPublicationRevision:0 } });expect(activated.status(),await activated.text()).toBe(200);
    context = await browser.newContext({ storageState:identity });const page = await context.newPage();await page.goto(`${independent!.url}/#/projects/${installation.projectId}/run`);await expect(page.locator(".runtime-status-banner")).toContainText("在线 2 台");await expect(page.locator('[data-node-id="fixed-metric"] .dashboard-metric-value')).toContainText("66.2");await page.getByRole("button",{ name:"选择设备 DEVICE-002",exact:true }).click();await expect(page.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.3");await page.screenshot({ path:testInfo.outputPath("downloaded-sqlite-runtime.png") });
  } finally { await context?.close();await api?.dispose();await independent?.close();await original.dispose();if (!sourceClosed) await source.dispose(); }
});
