import { test,expect,request as apiRequest } from "@playwright/test";
import { DatabaseSync } from "node:sqlite";
import { randomBytes } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import { unzipSync } from "fflate";
import { nodeRuntimeFixture } from "./node-runtime-fixture";
import { createDemo } from "./demo";

test("configure private SQLite queries through UI, keep live data and alarms without viewers, and import frozen query references",async ({ browser },testInfo) => {
  test.setTimeout(120000);const databasePath = testInfo.outputPath("equipment.sqlite");await mkdir(dirname(databasePath),{ recursive:true });const db = new DatabaseSync(databasePath);
  db.exec("PRAGMA journal_mode=WAL; CREATE TABLE equipment(assetId TEXT PRIMARY KEY,temperature REAL,pressure REAL,status TEXT,alarmLevel INTEGER,observedAt INTEGER)");
  for (const assetId of ["DEVICE-001","DEVICE-002"]) db.prepare("INSERT INTO equipment VALUES(?,42.5,24,'running',0,?)").run(assetId,Date.now());let stale = false;
  const timer = setInterval(() => db.prepare("UPDATE equipment SET observedAt=?").run(Date.now()-(stale ? 60000:0)),100);
  const runtime = await nodeRuntimeFixture(testInfo);let api = await apiRequest.newContext({ baseURL:runtime.url });const contexts:Array<Awaited<ReturnType<typeof browser.newContext>>> = [];
  try {
    expect((await api.post("/api/v1/auth/bootstrap",{ headers:{ "x-bootstrap-token":runtime.bootstrap },data:{ email:"sqlite-runtime@example.invalid",password:randomBytes(24).toString("hex"),displayName:"SQLite runtime" } })).status()).toBe(201);
    const demo = await createDemo(api,true),base = `/api/v1/projects/${demo.projectId}`,source = (await (await api.get(`${base}/data-sources`)).json()).dataSources[0];
    for (const asset of demo.assets) for (const binding of (await (await api.get(`${base}/assets/${asset.id}/data-bindings`)).json()).dataBindings) expect((await api.patch(`${base}/assets/${asset.id}/data-bindings/${binding.id}`,{ data:{ dataSourceId:source.id,sourcePath:`$.records.${asset.assetId}.${binding.metricKey}` } })).status()).toBe(200);
    const sql = "SELECT assetId,temperature,pressure,status,alarmLevel,observedAt FROM equipment ORDER BY assetId",environment = { version:1,endpoints:{},credentials:{},sqliteQueries:{ equipment:{ projectIds:[demo.projectId],databasePath:"../equipment.sqlite",sql,parameters:[],tables:{ equipment:["assetId","temperature","pressure","status","alarmLevel","observedAt"] },rowKey:"assetId",maxRows:10 } } };
    await runtime.setSources(environment);const identity = await api.storageState();await api.dispose();let url = await runtime.restart();api = await apiRequest.newContext({ baseURL:url,storageState:identity });
    const editor = await browser.newContext({ storageState:identity });contexts.push(editor);const editPage = await editor.newPage();await editPage.goto(`${url}/#/projects/${demo.projectId}/canvas`);await editPage.getByRole("button",{ name:"数据源",exact:true }).click();await editPage.getByRole("button",{ name:new RegExp(source.name) }).click();
    await editPage.getByRole("combobox",{ name:"连接类型",exact:true }).selectOption("sqlite_query");await editPage.getByLabel("私有查询引用",{ exact:true }).fill("equipment");await editPage.getByLabel("轮询周期（秒）",{ exact:true }).fill("1");await editPage.getByLabel("查询总超时（毫秒）",{ exact:true }).fill("1000");await editPage.getByLabel("数据时间戳路径（可选）",{ exact:true }).fill("$.records.DEVICE-001.observedAt");await editPage.getByLabel("源时间格式",{ exact:true }).selectOption("unix_ms");await editPage.getByRole("combobox",{ name:"采集方式",exact:true }).selectOption("continuous");
    await editPage.getByRole("button",{ name:"保存修改",exact:true }).click();await editPage.getByRole("button",{ name:"测试连接并发现字段",exact:true }).click();await expect(editPage.locator(".data-source-probe-result")).toBeVisible();await expect(editPage.locator(".data-source-probe-result")).toContainText("temperature");await expect(editPage.locator(".data-source-runtime-summary")).toContainText("持续采集");await editPage.screenshot({ path:testInfo.outputPath("sqlite-query-configuration.png") });
    const saved = (await (await api.get(`${base}/data-sources`)).json()).dataSources.find((item:{id:string}) => item.id === source.id);expect(saved).toMatchObject({ sourceType:"sqlite_query",config:{ queryRef:"equipment",collectionMode:"continuous",url:"" } });expect(saved.config).not.toHaveProperty("endpointRef");expect(JSON.stringify(saved)).not.toContain(databasePath);expect(JSON.stringify(saved)).not.toContain(sql);
    await editor.close();contexts.shift();const alarmConfig = (await (await api.get(`${base}/alarm-rules`)).json());expect((await api.put(`${base}/alarm-rules`,{ data:{ expectedRuntimeRevision:alarmConfig.runtimeRevision,rules:[{ id:"sql-temperature",name:"SQL temperature",assetId:"DEVICE-001",enabled:true,severity:"warning",message:"SQL high",recoveryCondition:null,condition:{ op:"gt",left:{ kind:"metric",assetId:"DEVICE-001",metricKey:"temperature" },right:{ kind:"literal",value:60 } } }] } })).status()).toBe(200);
    db.prepare("UPDATE equipment SET temperature=68.5 WHERE assetId='DEVICE-001'").run();const alarms = async () => (await (await api.get(`${base}/alarms`)).json());await expect.poll(async () => (await alarms()).active.length).toBe(1);await expect.poll(async () => (await (await api.get(`${base}/telemetry/history?assetId=DEVICE-001&metricKey=temperature`)).json()).records.some((row:{value:number;quality:string}) => row.value === 68.5 && row.quality === "good")).toBe(true);
    const pages = [];
    for (let index=0;index<2;index++) { const context = await browser.newContext({ storageState:identity });contexts.push(context);const page = await context.newPage();pages.push(page);await page.goto(`${url}/#/projects/${demo.projectId}/preview`);await expect(page.locator(".runtime-status-banner")).toContainText("在线 2 台");await page.getByRole("button",{ name:"选择设备 DEVICE-001",exact:true }).click();await expect(page.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.5"); }
    const status = (await (await api.get(`${base}/runtime/sources`)).json()).sources.filter((item:{id:string}) => item.id === source.id);expect(status).toHaveLength(1);expect(status[0]).toMatchObject({ mode:"continuous",subscribers:2 });
    stale = true;await expect(pages[1].locator(".runtime-status-banner")).toContainText("陈旧");await expect.poll(async () => (await alarms()).active[0]?.confirmation).toBe("unknown");stale = false;await expect(pages[1].locator(".runtime-status-banner")).toContainText("在线 2 台");
    db.prepare("UPDATE equipment SET temperature=NULL WHERE assetId='DEVICE-001'").run();await expect(pages[1].locator('[data-node-id="selected-metric"] [data-binding-state]')).toHaveAttribute("data-binding-state","null");db.prepare("UPDATE equipment SET temperature=68.5 WHERE assetId='DEVICE-001'").run();await expect(pages[1].locator('[data-node-id="selected-metric"] [data-binding-state]')).toHaveAttribute("data-binding-state","live");await pages[1].screenshot({ path:testInfo.outputPath("sqlite-query-live.png") });
    while (contexts.length) await contexts.shift()!.close();const draft = (await (await api.get(`${base}/publication-draft`)).json()).draft,freeze = await api.post(`${base}/versions`,{ data:{ expectedRuntimeRevision:draft.runtimeRevision,label:"Frozen read-only query" } });expect(freeze.status(),await freeze.text()).toBe(201);const version = (await freeze.json()).version;
    const exported = await api.get(`${base}/versions/${version.id}/package`);expect(exported.status()).toBe(200);const zip = await exported.body(),manifestText = new TextDecoder().decode(unzipSync(zip)["manifest.json"]),manifest = JSON.parse(manifestText);expect(manifest.snapshot.requiredCapabilities).toContain("sqlite-query-source-v1");expect(manifest.requiredEndpoints.some((item:{endpointRef:string}) => item.endpointRef === "equipment")).toBe(true);expect(manifestText).not.toContain(sql);expect(manifestText).not.toContain("equipment.sqlite");
    const checked = await api.post("/api/v1/project-packages",{ data:zip,headers:{ "content-type":"application/zip" } });expect(checked.status(),await checked.text()).toBe(201);const installed = await api.post("/api/v1/project-packages/install",{ data:{ inspectionId:(await checked.json()).inspection.id,projectName:"Imported SQLite" } });expect(installed.status(),await installed.text()).toBe(201);const installation = (await installed.json()).installation,importedBase = `/api/v1/projects/${installation.projectId}`;
    expect((await api.post(`${importedBase}/versions/${installation.versionId}/activate`,{ data:{ expectedPublicationRevision:0 } })).status()).toBe(409);
    environment.sqliteQueries.equipment.projectIds.push(installation.projectId);await runtime.setSources(environment);await api.dispose();url = await runtime.restart();api = await apiRequest.newContext({ baseURL:url,storageState:identity });const activation = await api.post(`${importedBase}/versions/${installation.versionId}/activate`,{ data:{ expectedPublicationRevision:0 } });expect(activation.status(),await activation.text()).toBe(200);
    const context = await browser.newContext({ storageState:identity });contexts.push(context);const page = await context.newPage();await page.goto(`${url}/#/projects/${installation.projectId}/run`);await expect(page.locator(".runtime-status-banner")).toContainText("在线 2 台");await page.getByRole("button",{ name:"选择设备 DEVICE-001",exact:true }).click();await expect(page.locator('[data-node-id="selected-metric"] .dashboard-metric-value')).toContainText("68.5");await page.screenshot({ path:testInfo.outputPath("sqlite-query-imported-runtime.png") });
  } finally { for (const context of contexts) await context.close();await api.dispose();await runtime.dispose();clearInterval(timer);db.close(); }
});
