import assert from 'node:assert/strict';
import { AnimationClip, AnimationMixer, LoopOnce, LoopRepeat, NumberKeyframeTrack, Object3D } from 'three';
import { createNativePlayback } from '../src/scene/native-playback';

const target = new Object3D();
const mixer = new AnimationMixer(target);
const clip = new AnimationClip('native', 9, [new NumberKeyframeTrack('.position[x]', [0, 3.6, 7.9, 9], [0, 3, 7, 8])]);
const action = mixer.clipAction(clip).play();
const playback = createNativePlayback([{ mixer, actions: [action] }]);
assert.equal(action.loop, LoopOnce);
assert.equal(action.clampWhenFinished, true);
assert.deepEqual(playback.progress(), { time: 0, duration: 9, finished: false });
mixer.update(3.6);
assert.ok(Math.abs(target.position.x - 3) < 1e-6, 'Native keyframes are retained');
playback.seek(7.9);
assert.ok(Math.abs(target.position.x - 7) < 1e-6, 'Seeking evaluates the actual native track');
mixer.update(5);
assert.deepEqual(playback.progress(), { time: 9, duration: 9, finished: true });
assert.equal(target.position.x, 8, 'One-shot playback holds its final pose');
mixer.update(20);
assert.equal(target.position.x, 8, 'One-shot playback does not loop on completion');
playback.seek(0);
assert.equal(target.position.x, 0, 'Explicit replay resets the native action');
mixer.update(1);
assert.ok(target.position.x > 0 && target.position.x < 3, 'Replay advances again after completion');
playback.seek(9);
assert.deepEqual(playback.progress(), { time: 9, duration: 9, finished: true });
for (const invalid of [-1, 9.1, NaN, Infinity]) assert.throws(() => playback.seek(invalid), /超出有效范围/);
assert.throws(() => createNativePlayback([]), /没有可播放的原生动画/);
assert.deepEqual(Array.from(clip.tracks[0].values), [0, 3, 7, 8], 'Transport never rewrites source tracks');
mixer.stopAllAction();
mixer.uncacheRoot(target);

const repeatTarget = new Object3D();
const repeatMixer = new AnimationMixer(repeatTarget);
const repeatAction = repeatMixer.clipAction(clip).play();
const repeatPlayback = createNativePlayback([{ mixer: repeatMixer, actions: [repeatAction] }], 'repeat');
assert.equal(repeatAction.loop, LoopRepeat);
assert.equal(repeatAction.repetitions, Infinity);
assert.equal(repeatAction.clampWhenFinished, false);
for (let cycle = 0; cycle < 4; cycle++) {
  repeatMixer.update(7.9);
  assert.ok(Math.abs(repeatTarget.position.x - 7) < 1e-6, 'Every cycle follows the original placement keyframe');
  repeatMixer.update(1.1);
  assert.ok(Math.abs(repeatPlayback.progress().time) < 1e-6, 'Completion immediately begins the next native cycle');
  assert.equal(repeatPlayback.progress().finished, false, 'Repeating playback never reports completion');
  assert.equal(repeatTarget.position.x, 0, 'The clip restarts at its original first pose');
}
repeatPlayback.seek(3.6);
assert.ok(Math.abs(repeatTarget.position.x - 3) < 1e-6, 'Phase inspection still evaluates the native track');
assert.equal(repeatAction.loop, LoopRepeat, 'Seeking retains the repeat mode');
repeatAction.paused = true;
repeatMixer.update(20);
assert.equal(repeatPlayback.progress().time, 3.6, 'Pause holds the selected phase');
repeatAction.paused = false;
repeatMixer.update(9);
assert.ok(Math.abs(repeatPlayback.progress().time - 3.6) < 1e-6, 'Resume continues looping');
repeatPlayback.seek(0);
assert.deepEqual(repeatPlayback.progress(), { time: 0, duration: 9, finished: false });
repeatMixer.update(10);
assert.equal(repeatPlayback.progress().time, 1, 'Explicit replay retains automatic repetition');
assert.deepEqual(Array.from(clip.tracks[0].values), [0, 3, 7, 8], 'Looping never rewrites source tracks');
repeatMixer.stopAllAction();
repeatMixer.uncacheRoot(repeatTarget);
console.log('native-playback: original interpolation, seek, one-shot hold, repeat, pause/resume and replay passed');
