import assert from 'node:assert/strict';
import * as THREE from 'three';
import { createSceneDecoration, parseSceneDecorations, sceneDecorationBudget, SCENE_DECORATION_LIMITS } from '../../../shared/scene-decorations';
import { DecorationManager } from '../src/scene/decoration-manager';
const kinds=['tree','shrub','river','military-truck','military-tent','military-radar','military-armored'];
const defs=kinds.map((kind,i)=>createSceneDecoration(`d${i}`,kind));
assert.equal(parseSceneDecorations([]).ok,true);
assert.equal(parseSceneDecorations(defs).ok,true);
const invalid=(value)=>assert.equal(parseSceneDecorations(value).ok,false);
invalid([defs[0],defs[0]]); invalid([{...defs[0],extra:1}]); invalid([{...defs[0],color:'#bad'}]);
invalid([{...defs[0],id:'bad\n'}]);invalid([{...defs[0],color:'#aabbcc\n'}]);invalid([{...defs[0],accentColor:'#aabbcc\n'}]);
invalid([{...defs[0],river:defs[2].river}]);invalid([{...defs[2],river:{...defs[2].river,points:[[0,0,0],[0,1,0]]}}]);
invalid([{...defs[2],river:{...defs[2].river,points:[[0,0,0],[2,0,0],[1,0,0]]}}]);
invalid([{...defs[2],river:{...defs[2].river,points:[[0,0,0],[2,0,2],[4,0,0],[2,0,-2],[0,0,0]]}}]);
invalid([{...defs[0],transform:{...defs[0].transform,scale:[0,1,1]}}]);
invalid([{...defs[0],transform:{...defs[0].transform,scale:[0.0009,1,1]}}]);
assert.equal(SCENE_DECORATION_LIMITS.minimumScale,0.001);
assert.equal(parseSceneDecorations([{...defs[0],transform:{...defs[0].transform,scale:[0.001,1,1]}}]).ok,true);
invalid([{...defs[0],seed:2**32}]);
const bend=(points,width=1)=>({...defs[2],river:{...defs[2].river,points,width}});
assert.equal(parseSceneDecorations([bend([[0,0,0],[5,0,0],[5,0,5]])]).ok,true,'right angle is valid');
invalid([bend([[0,0,0],[5,0,0],[4,0,0.1]])]);
invalid([bend([[0,0,0],[1,0,0],[1,0,1]],5)]);
invalid([bend([[0,0,0],[5,0,0],[5,0,5],[0,0,5]],6)]);
const parentA=new THREE.Group(), parentB=new THREE.Group();
const a=new DecorationManager(parentA),b=new DecorationManager(parentB);
a.reconcile(defs);b.reconcile(defs);
const budget=sceneDecorationBudget(defs),stats=a.diagnostics();
assert.equal(stats.decorationCount,defs.length);assert.ok(stats.meshCount<=budget.meshes);assert.ok(stats.triangleCount<=budget.triangles);
assert.equal(budget.animatedInstances,1);
for(const d of defs){const manager=new DecorationManager(new THREE.Group());manager.reconcile([d]);const actual=manager.diagnostics(),limit=sceneDecorationBudget([d]);assert.ok(actual.meshCount<=limit.meshes,`${d.kind}: mesh budget`);assert.ok(actual.triangleCount<=limit.triangles,`${d.kind}: triangle budget ${actual.triangleCount}/${limit.triangles}`);manager.dispose();}
assert.deepEqual(a.getPickObjects().map(o=>o.userData.sceneDecorationId),defs.map(d=>d.id));
const first=a.getPickObjects()[0],second=b.getPickObjects()[0];
assert.notEqual(first.children[0].material,second.children[0].material);
const geo=first.children[0].geometry;const position=Array.from(geo.getAttribute('position').array);
assert.deepEqual(position,Array.from(second.children[0].geometry.getAttribute('position').array),'seed produces deterministic geometry');
a.reconcile(structuredClone(defs));assert.equal(a.getPickObjects()[0],first,'unchanged definition retains root');
let disposed=0;const oldDispose=geo.dispose.bind(geo);geo.dispose=()=>{disposed++;oldDispose();};
assert.throws(()=>a.reconcile([...defs,{...defs[0],id:'invalid',river:defs[2].river}]),/无效/);
assert.equal(a.getPickObjects()[0],first);assert.equal(disposed,0);
const river=a.getPickObjects()[2],riverSurface=river.children[0];
const tent=a.getPickObjects()[4];const tentRoof=tent.getObjectByName('tent');
assert.equal(tentRoof.rotation.y,0);assert.equal(tentRoof.position.z,-1.5);
const bounds=a.getBounds();assert.ok(bounds.max.x>=5 && bounds.min.z<=-0.9 && bounds.max.z>=0.9);
const phase=riverSurface.material.uniforms.uPhase.value;
a.update(1,false,1);assert.equal(riverSurface.material.uniforms.uPhase.value,phase);
a.update(1,true,1);assert.notEqual(riverSurface.material.uniforms.uPhase.value,phase);
a.reconcile([defs[2]]);assert.equal(disposed,1);assert.equal(parentA.children.length,1);
a.dispose();b.dispose();assert.equal(parentA.children.length,0);assert.equal(parentB.children.length,0);
assert.throws(()=>a.reconcile([]),/已释放/);
console.log('Scene decorations tests passed: parser, budgets, deterministic geometry, isolation, incremental reconcile, rollback, disposal, river bounds and pause.');
