// Generated by scripts/generate-workshop-models.mjs. Editable instances, meters / Y-up.
import type { StandaloneSceneInstance, StandaloneSceneSettings } from './standalone-3d';
export const workshopSettings = {
  "animationSpeed": 1,
  "autoRotate": false,
  "backgroundColor": "#152431",
  "backgroundOpacity": 1,
  "cameraFov": 38,
  "cameraView": "isometric",
  "environmentLightColor": "#e0ecf5",
  "environmentLightIntensity": 0.62,
  "keyLightColor": "#fff2db",
  "keyLightIntensity": 2.1,
  "modelScale": 1.7,
  "playAnimations": true,
  "rotationSpeed": 0.35,
  "showGrid": false
} satisfies StandaloneSceneSettings;
export const workshopInstances = [
  {
    "id": "workshop-001",
    "modelAssetId": "builtin:workshop-floor-v3",
    "label": "车间地坪 · 28 × 20 m",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 0,
    "transform": {
      "position": [
        0,
        0,
        0
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-002",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 -12.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 1,
    "transform": {
      "position": [
        -12.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-003",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 -10",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 2,
    "transform": {
      "position": [
        -10,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-004",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 -7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 3,
    "transform": {
      "position": [
        -7.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-005",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 -5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 4,
    "transform": {
      "position": [
        -5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-006",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 -2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 5,
    "transform": {
      "position": [
        -2.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-007",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 0",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 6,
    "transform": {
      "position": [
        0,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-008",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 7,
    "transform": {
      "position": [
        2.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-009",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 8,
    "transform": {
      "position": [
        5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-010",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 9,
    "transform": {
      "position": [
        7.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-011",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 10",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 10,
    "transform": {
      "position": [
        10,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-012",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "北侧墙 12.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 11,
    "transform": {
      "position": [
        12.5,
        0,
        -10
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8333333333333334,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-013",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 -14/-7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 12,
    "transform": {
      "position": [
        -14,
        0,
        -7.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-014",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 -14/-2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 13,
    "transform": {
      "position": [
        -14,
        0,
        -2.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-015",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 -14/2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 14,
    "transform": {
      "position": [
        -14,
        0,
        2.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-016",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 -14/7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 15,
    "transform": {
      "position": [
        -14,
        0,
        7.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-017",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 14/-7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 16,
    "transform": {
      "position": [
        14,
        0,
        -7.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-018",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 14/-2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 17,
    "transform": {
      "position": [
        14,
        0,
        -2.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-019",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 14/2.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 18,
    "transform": {
      "position": [
        14,
        0,
        2.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-020",
    "modelAssetId": "builtin:workshop-wall-v2",
    "label": "侧墙 14/7.5",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 19,
    "transform": {
      "position": [
        14,
        0,
        7.5
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.6666666666666667,
        0.58,
        1
      ]
    }
  },
  {
    "id": "workshop-021",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 -12/-8",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 20,
    "transform": {
      "position": [
        -12,
        0,
        -8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-022",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 -12/0",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 21,
    "transform": {
      "position": [
        -12,
        0,
        0
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-023",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 -12/8",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 22,
    "transform": {
      "position": [
        -12,
        0,
        8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-024",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 12/-8",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 23,
    "transform": {
      "position": [
        12,
        0,
        -8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-025",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 12/0",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 24,
    "transform": {
      "position": [
        12,
        0,
        0
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-026",
    "modelAssetId": "builtin:workshop-column-v2",
    "label": "结构柱 12/8",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 25,
    "transform": {
      "position": [
        12,
        0,
        8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-027",
    "modelAssetId": "builtin:workshop-rack-v2",
    "label": "仓储货架 -10",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 26,
    "transform": {
      "position": [
        -10,
        0,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-028",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/0/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 27,
    "transform": {
      "position": [
        -10.85,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-029",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/0/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 28,
    "transform": {
      "position": [
        -9.15,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-030",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/1/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 29,
    "transform": {
      "position": [
        -10.85,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-031",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/1/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 30,
    "transform": {
      "position": [
        -9.15,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-032",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/2/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 31,
    "transform": {
      "position": [
        -10.85,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-033",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -10/2/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 32,
    "transform": {
      "position": [
        -9.15,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-034",
    "modelAssetId": "builtin:workshop-rack-v2",
    "label": "仓储货架 -5",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 33,
    "transform": {
      "position": [
        -5,
        0,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-035",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/0/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 34,
    "transform": {
      "position": [
        -5.85,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-036",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/0/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 35,
    "transform": {
      "position": [
        -4.15,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-037",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/1/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 36,
    "transform": {
      "position": [
        -5.85,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-038",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/1/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 37,
    "transform": {
      "position": [
        -4.15,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-039",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/2/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 38,
    "transform": {
      "position": [
        -5.85,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-040",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 -5/2/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 39,
    "transform": {
      "position": [
        -4.15,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-041",
    "modelAssetId": "builtin:workshop-rack-v2",
    "label": "仓储货架 0",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 40,
    "transform": {
      "position": [
        0,
        0,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-042",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/0/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 41,
    "transform": {
      "position": [
        -0.85,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-043",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/0/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 42,
    "transform": {
      "position": [
        0.85,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-044",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/1/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 43,
    "transform": {
      "position": [
        -0.85,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-045",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/1/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 44,
    "transform": {
      "position": [
        0.85,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-046",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/2/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 45,
    "transform": {
      "position": [
        -0.85,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-047",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 0/2/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 46,
    "transform": {
      "position": [
        0.85,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-048",
    "modelAssetId": "builtin:workshop-rack-v2",
    "label": "仓储货架 5",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 47,
    "transform": {
      "position": [
        5,
        0,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-049",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/0/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 48,
    "transform": {
      "position": [
        4.15,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-050",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/0/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 49,
    "transform": {
      "position": [
        5.85,
        0.31,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-051",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/1/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 50,
    "transform": {
      "position": [
        4.15,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-052",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/1/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 51,
    "transform": {
      "position": [
        5.85,
        1.18,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-053",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/2/-0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 52,
    "transform": {
      "position": [
        4.15,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-054",
    "modelAssetId": "builtin:workshop-box-v2",
    "label": "货架箱 5/2/0.85",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 53,
    "transform": {
      "position": [
        5.85,
        2.05,
        -8.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-055",
    "modelAssetId": "builtin:workshop-production-machine-v2",
    "label": "产线 1-1 · 自动设备",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 54,
    "transform": {
      "position": [
        -6.65,
        0,
        -3.3
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-056",
    "modelAssetId": "builtin:workshop-robot-arm-v2",
    "label": "产线 1-1 · 机械臂",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 55,
    "transform": {
      "position": [
        -4.3,
        0,
        -2.8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-057",
    "modelAssetId": "builtin:workshop-workbench-v2",
    "label": "产线 1-1 · 工作台",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 56,
    "transform": {
      "position": [
        -6.3,
        0,
        -1.2499999999999998
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-058",
    "modelAssetId": "builtin:workshop-production-machine-v2",
    "label": "产线 1-2 · 自动设备",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 57,
    "transform": {
      "position": [
        -6.65,
        0,
        2.9
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-059",
    "modelAssetId": "builtin:workshop-robot-arm-v2",
    "label": "产线 1-2 · 机械臂",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 58,
    "transform": {
      "position": [
        -4.3,
        0,
        3.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-060",
    "modelAssetId": "builtin:workshop-workbench-v2",
    "label": "产线 1-2 · 工作台",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 59,
    "transform": {
      "position": [
        -6.3,
        0,
        4.95
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-061",
    "modelAssetId": "builtin:workshop-production-machine-v2",
    "label": "产线 2-1 · 自动设备",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 60,
    "transform": {
      "position": [
        3.9499999999999997,
        0,
        -3.3
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-062",
    "modelAssetId": "builtin:workshop-robot-arm-v2",
    "label": "产线 2-1 · 机械臂",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 61,
    "transform": {
      "position": [
        6.3,
        0,
        -2.8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-063",
    "modelAssetId": "builtin:workshop-workbench-v2",
    "label": "产线 2-1 · 工作台",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 62,
    "transform": {
      "position": [
        4.3,
        0,
        -1.2499999999999998
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-064",
    "modelAssetId": "builtin:workshop-production-machine-v2",
    "label": "产线 2-2 · 自动设备",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 63,
    "transform": {
      "position": [
        3.9499999999999997,
        0,
        2.9
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-065",
    "modelAssetId": "builtin:workshop-robot-arm-v2",
    "label": "产线 2-2 · 机械臂",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 64,
    "transform": {
      "position": [
        6.3,
        0,
        3.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-066",
    "modelAssetId": "builtin:workshop-workbench-v2",
    "label": "产线 2-2 · 工作台",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 65,
    "transform": {
      "position": [
        4.3,
        0,
        4.95
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-067",
    "modelAssetId": "builtin:workshop-agv-v2",
    "label": "AGV-01 · 中央运输通道",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 66,
    "transform": {
      "position": [
        0,
        0,
        -4.8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-068",
    "modelAssetId": "builtin:workshop-agv-v2",
    "label": "AGV-02 · 东侧运输通道",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 67,
    "transform": {
      "position": [
        11,
        0,
        -4.8
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-069",
    "modelAssetId": "builtin:workshop-partition-v2",
    "label": "检验室 · 前隔断",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 68,
    "transform": {
      "position": [
        8.9,
        0,
        -6
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.95,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-070",
    "modelAssetId": "builtin:workshop-partition-v2",
    "label": "检验室 · 左隔断",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 69,
    "transform": {
      "position": [
        7.45,
        0,
        -8
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1.33,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-071",
    "modelAssetId": "builtin:workshop-door-v2",
    "label": "检验室 · 工业门",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 70,
    "transform": {
      "position": [
        11.25,
        0,
        -6
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-072",
    "modelAssetId": "builtin:workshop-workbench-v2",
    "label": "检验室 · 检验长桌",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 71,
    "transform": {
      "position": [
        10.7,
        0,
        -8.3
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        0.8,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-073",
    "modelAssetId": "builtin:workshop-alarm-light-v2",
    "label": "入口三色报警灯",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 72,
    "transform": {
      "position": [
        -12,
        1.8,
        7.7
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-074",
    "modelAssetId": "builtin:workshop-wall-camera-v2",
    "label": "北墙监控 -9",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 73,
    "transform": {
      "position": [
        -9,
        2.55,
        -9.86
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-075",
    "modelAssetId": "builtin:workshop-wall-camera-v2",
    "label": "北墙监控 3",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 74,
    "transform": {
      "position": [
        3,
        2.55,
        -9.86
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-076",
    "modelAssetId": "builtin:workshop-wall-camera-v2",
    "label": "北墙监控 12",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 75,
    "transform": {
      "position": [
        12,
        2.55,
        -9.86
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-077",
    "modelAssetId": "builtin:workshop-wall-camera-v2",
    "label": "西墙监控",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 76,
    "transform": {
      "position": [
        -13.84,
        1.7,
        2
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-078",
    "modelAssetId": "builtin:workshop-conveyor-v2",
    "label": "滚筒输送线 -5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 77,
    "transform": {
      "position": [
        -2.5999999999999996,
        0,
        -1.6999999999999997
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-079",
    "modelAssetId": "builtin:workshop-tool-cabinet-v2",
    "label": "工具柜 -5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 78,
    "transform": {
      "position": [
        -8.35,
        0,
        -3
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-080",
    "modelAssetId": "builtin:workshop-safety-fence-v2",
    "label": "机械臂后侧围栏 -5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 79,
    "transform": {
      "position": [
        -3.75,
        0,
        -4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-081",
    "modelAssetId": "builtin:workshop-conveyor-v2",
    "label": "滚筒输送线 -5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 80,
    "transform": {
      "position": [
        -2.5999999999999996,
        0,
        4.5
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-082",
    "modelAssetId": "builtin:workshop-tool-cabinet-v2",
    "label": "工具柜 -5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 81,
    "transform": {
      "position": [
        -8.35,
        0,
        3.1999999999999997
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-083",
    "modelAssetId": "builtin:workshop-safety-fence-v2",
    "label": "机械臂后侧围栏 -5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 82,
    "transform": {
      "position": [
        -3.75,
        0,
        2.2
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-084",
    "modelAssetId": "builtin:workshop-conveyor-v2",
    "label": "滚筒输送线 5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 83,
    "transform": {
      "position": [
        8,
        0,
        -1.6999999999999997
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-085",
    "modelAssetId": "builtin:workshop-tool-cabinet-v2",
    "label": "工具柜 5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 84,
    "transform": {
      "position": [
        2.25,
        0,
        -3
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-086",
    "modelAssetId": "builtin:workshop-safety-fence-v2",
    "label": "机械臂后侧围栏 5.3/-2.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 85,
    "transform": {
      "position": [
        6.85,
        0,
        -4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-087",
    "modelAssetId": "builtin:workshop-conveyor-v2",
    "label": "滚筒输送线 5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 86,
    "transform": {
      "position": [
        8,
        0,
        4.5
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-088",
    "modelAssetId": "builtin:workshop-tool-cabinet-v2",
    "label": "工具柜 5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 87,
    "transform": {
      "position": [
        2.25,
        0,
        3.1999999999999997
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-089",
    "modelAssetId": "builtin:workshop-safety-fence-v2",
    "label": "机械臂后侧围栏 5.3/3.4",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 88,
    "transform": {
      "position": [
        6.85,
        0,
        2.2
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-090",
    "modelAssetId": "builtin:workshop-pallet-v2",
    "label": "入库待检物料 -10.8",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 89,
    "transform": {
      "position": [
        -10.8,
        0,
        7.5
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-091",
    "modelAssetId": "builtin:workshop-pallet-v2",
    "label": "入库待检物料 -8.7",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 90,
    "transform": {
      "position": [
        -8.7,
        0,
        7.5
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-092",
    "modelAssetId": "builtin:workshop-pallet-v2",
    "label": "入库待检物料 -6.6",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 91,
    "transform": {
      "position": [
        -6.6,
        0,
        7.5
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-093",
    "modelAssetId": "builtin:workshop-electrical-cabinet-v2",
    "label": "动力控制柜 -12.5",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 92,
    "transform": {
      "position": [
        -12.5,
        0,
        -5.45
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-094",
    "modelAssetId": "builtin:workshop-electrical-cabinet-v2",
    "label": "动力控制柜 -10.7",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 93,
    "transform": {
      "position": [
        -10.7,
        0,
        -5.45
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-095",
    "modelAssetId": "builtin:workshop-air-compressor-v2",
    "label": "压缩空气供应站",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 94,
    "transform": {
      "position": [
        -11.5,
        0,
        4.4
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-096",
    "modelAssetId": "builtin:workshop-fire-station-v2",
    "label": "西墙消防站",
    "assetId": null,
    "visible": true,
    "renderMode": "interactive",
    "sortOrder": 95,
    "transform": {
      "position": [
        -13.8,
        0,
        -1.2
      ],
      "rotation": [
        0,
        90,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-097",
    "modelAssetId": "builtin:workshop-utility-gantry-v2",
    "label": "架空管线 -5.3",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 96,
    "transform": {
      "position": [
        -5.3,
        0,
        0.2
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  },
  {
    "id": "workshop-098",
    "modelAssetId": "builtin:workshop-utility-gantry-v2",
    "label": "架空管线 5.3",
    "assetId": null,
    "visible": true,
    "renderMode": "background",
    "sortOrder": 97,
    "transform": {
      "position": [
        5.3,
        0,
        0.2
      ],
      "rotation": [
        0,
        0,
        0
      ],
      "scale": [
        1,
        1,
        1
      ]
    }
  }
] satisfies StandaloneSceneInstance[];
